# Generated by Django 5.2.8 on 2025-11-11 04:42

import django.db.models.deletion # Importamos el módulo de eliminación
import uuid # Importamos el módulo uuid para generar IDs únicos
from django.conf import settings # Importamos el módulo de configuración
from django.db import migrations, models # Importamos el módulo de migraciones y modelos

# Clase Migration que define la migración inicial
class Migration(migrations.Migration):

    initial = True # Indica que es la migración inicial

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), # Indica la dependencia del modelo de usuario
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente', # Nombre del modelo
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(help_text='Email único para identificar al cliente.', max_length=254, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido', # Nombre del modelo
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ID único para el portal del cliente.', unique=True)),
                ('estado', models.CharField(choices=[('solicitud', 'Solicitud Recibida'), ('cotizado', 'Cotizado y Enviado'), ('aceptado', 'Aceptado por Cliente'), ('pago_confirmado', 'Pago Confirmado'), ('despachado', 'Despachado'), ('completado', 'Completado'), ('rechazado', 'Rechazado por Cliente')], default='solicitud', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion.cliente')),
                ('vendedor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsPedido', # Nombre del modelo
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.pedido')),
            ],
        ),
    ]
