# Generated by Django 5.2.8 on 2025-11-12 04:21

from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración

    dependencies = [
        ('gestion', '0001_initial'), # Dependencia de la migración inicial
    ]

    operations = [
        migrations.AddField(
            model_name='pedido', # Modelo al que se le agrega el campo
            name='costo_envio_estimado', # Nombre del campo
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo estimado del envío para la cotización.', max_digits=10), # Definición del campo
        ),
        migrations.AddField(
            model_name='pedido', # Modelo al que se le agrega el campo
            name='porcentaje_urgencia', # Nombre del campo
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de recargo por urgencia (ej. 5.5 para 5.5%)', max_digits=5), # Definición del campo
        ),
    ]
