# Generated by Django 5.2.8 on 2025-11-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio_estimado',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo estimado del envío para la cotización.', max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='porcentaje_urgencia',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de recargo por urgencia (ej. 5.5 para 5.5%)', max_digits=5),
        ),
    ]
