# Generated by Django 5.2.8 on 2025-11-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_pedido_costo_envio_estimado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_despacho',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='transportista',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
