# Generated by Django 5.2.8 on 2025-11-13 01:33
    
from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    # Dependencias de la migración
    dependencies = [
        ('gestion', '0002_pedido_costo_envio_estimado_and_more'), # Dependencia de la migración anterior
    ]

    # Operaciones de la migración
    operations = [
        migrations.AddField(
            model_name='pedido', # Modelo al que se le agrega el campo
            name='fecha_despacho', # Nombre del campo
            field=models.DateTimeField(blank=True, null=True), # Definición del campo
        ),
        migrations.AddField(
            model_name='pedido', # Modelo al que se le agrega el campo
            name='numero_guia', # Nombre del campo
            field=models.CharField(blank=True, max_length=100, null=True), # Definición del campo
        ),
        migrations.AddField(
            model_name='pedido', # Modelo al que se le agrega el campo
            name='transportista', # Nombre del campo
            field=models.CharField(blank=True, max_length=100, null=True), # Definición del campo
        ),
    ]
