# Generated by Django 5.2.8 on 2025-11-22 17:33

import django.db.models.deletion # Importamos el módulo de eliminación
from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    """Clase Migration que define la migración"""
    dependencies = [
        ('gestion', '0003_pedido_fecha_despacho_pedido_numero_guia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoFrecuente', # Nombre del modelo
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_referencia', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio referencial para el vendedor, no visible al cliente.', max_digits=10)),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto.', null=True)),
                ('categoria', models.CharField(blank=True, help_text='Categoría para agrupar en el frontend (ej. Herramientas, EPP).', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='itemspedido', # Modelo al que se le agrega el campo
            name='referencia', # Nombre del campo
            field=models.CharField(blank=True, help_text='URL del producto o Modelo/Marca si es manual.', max_length=500, null=True), # Definición del campo
        ),
        migrations.AddField(
            model_name='itemspedido', # Modelo al que se le agrega el campo
            name='tipo_origen', # Nombre del campo
            field=models.CharField(choices=[('LINK', 'Enlace Externo'), ('MANUAL', 'Ingreso Manual'), ('CATALOGO', 'Catálogo Frecuente')], default='MANUAL', max_length=20), # Definición del campo
        ),
        migrations.AddField(
            model_name='itemspedido', # Modelo al que se le agrega el campo
            name='producto_frecuente', # Nombre del campo
            field=models.ForeignKey(blank=True, help_text='Referencia al producto de catálogo si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.productofrecuente'), # Definición del campo
        ),
    ]
