# Generated by Django 5.2.8 on 2025-11-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_productofrecuente_itemspedido_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
