# Generated by Django 5.2.8 on 2025-11-22 17:36

from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    # Dependencias de la migración
    dependencies = [
        ('gestion', '0004_productofrecuente_itemspedido_referencia_and_more'), # Dependencia de la migración anterior
    ]

    # Operaciones de la migración
    operations = [
        migrations.AddField(
            model_name='cliente', # Modelo al que se le agrega el campo
            name='telefono', # Nombre del campo
            field=models.CharField(blank=True, max_length=50, null=True), # Definición del campo
        ),
    ]
