# Generated by Django 5.2.8 on 2025-11-23 14:06

from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    # Dependencias de la migración
    dependencies = [
        ('gestion', '0007_pedido_opciones_envio'),
    ]

    # Operaciones de la migración
    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_envio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nombre_transporte_custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='opciones_envio',
            field=models.JSONField(blank=True, default=dict, help_text="Almacena las opciones de envío calculadas (ej. {'STARKEN': 5000, 'BLUE': 4000})", null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
