# Generated by Django 5.2.8 on 2025-11-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_pedido_metodo_envio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemspedido',
            name='costo_unitario',
        ),
        migrations.AddField(
            model_name='itemspedido',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Costo neto de compra al proveedor', max_digits=10),
        ),
        migrations.AddField(
            model_name='itemspedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemspedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
