# Generated by Django 5.2.8 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_remove_itemspedido_costo_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemspedido',
            name='referencia',
            field=models.TextField(blank=True, help_text='URL del producto o Modelo/Marca si es manual.', null=True),
        ),
    ]
