# Generated by Django 5.2.8 manually

from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    # Dependencias de la migración
    dependencies = [
        ('gestion', '0009_remove_itemspedido_costo_unitario_and_more'),
    ]

    # Operaciones de la migración
    operations = [
        migrations.AlterField(
            model_name='itemspedido',
            name='referencia',
            field=models.TextField(blank=True, help_text='URL del producto o Modelo/Marca si es manual.', null=True),
        ),
    ]
