# Generated by Django 4.2.7 on 2025-12-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_itemspedido_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_retention_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último correo de retención enviado.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='retention_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('no_response', 'Sin Respuesta'), ('rejected', 'Rechazado / No Molestar'), ('recovered', 'Recuperado')], default='pending', max_length=20),
        ),
    ]
