# Generated by Django 4.2.7 on 2025-12-06 03:16

from django.db import migrations, models # Importamos el módulo de migraciones y modelos


class Migration(migrations.Migration): # Clase Migration que define la migración
    # Dependencias de la migración
    dependencies = [
        ('gestion', '0010_alter_itemspedido_referencia'),
    ]

    # Operaciones de la migración
    operations = [
        migrations.AddField(
            model_name='cliente',
            name='last_retention_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Fecha del último correo de retención enviado.', null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='retention_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('contacted', 'Contactado'), ('no_response', 'Sin Respuesta'), ('rejected', 'Rechazado / No Molestar'), ('recovered', 'Recuperado')], default='pending', max_length=20),
        ),
    ]
