# Generated by Django 4.2.7 on 2025-12-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_cliente_last_retention_email_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(default='', help_text='Apellidos del cliente (Ej. Pérez González)', max_length=255),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombres',
            field=models.CharField(default='', help_text='Nombres del cliente (Ej. Juan Andrés)', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text="Campo legado. Se eliminará tras validar 'nombres' y 'apellidos'.", max_length=255),
        ),
    ]
