# Generated by Django manually

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_cliente_apellidos_cliente_nombres_and_more'),
    ]

    operations = [
        # 1. Eliminar el campo legado 'nombre' (Full Name string)
        migrations.RemoveField(
            model_name='cliente',
            name='nombre',
        ),
        # 2. Renombrar 'nombres' (Plural) a 'nombre' (Singular) - Mantiene datos
        migrations.RenameField(
            model_name='cliente',
            old_name='nombres',
            new_name='nombre',
        ),
        # 3. Renombrar 'apellidos' (Plural) a 'apellido' (Singular) - Mantiene datos
        migrations.RenameField(
            model_name='cliente',
            old_name='apellidos',
            new_name='apellido',
        ),
        # 4. Asegurar que los nuevos nombres tengan la definición correcta (Help Text, Defaults)
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='', help_text='Primer nombre o nombres de pila (Ej. Juan Andrés)', max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(default='', help_text='Apellido o apellidos (Ej. Pérez González)', max_length=255),
        ),
    ]
