# Generated by Django 5.2.8 on 2025-11-12 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_precargar_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
